// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"game-ddz/internal/biz"
	"game-ddz/internal/conf"
	"game-ddz/internal/data"
	"game-ddz/internal/server"
	"game-ddz/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	gameRepo := data.NewgameRepo(dataData, logger)
	gameUsecase := biz.NewgameUsecase(gameRepo, logger)
	gameService := service.NewgameService(gameUsecase)
	httpServer := server.NewHTTPServer(confServer, gameService, logger)
	grpcServer := server.NewGRPCServer(confServer, gameService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
